// 30 天的驚喜內容庫存
export const surprisesData = [
  {
    date: "2026-02-06",
    title: "🌟 今日金句",
    content: "「成功不是終點，失敗也不是末日，最重要的是繼續前進的勇氣。」— 邱吉爾",
    category: "quote",
    tags: ["勵志", "名言"],
  },
  {
    date: "2026-02-07",
    title: "🎨 創意挑戰",
    content: "今天試試用非慣用手寫字或畫圖，你會發現大腦的另一面！",
    category: "challenge",
    tags: ["創意", "挑戰"],
  },
  {
    date: "2026-02-08",
    title: "🧠 冷知識",
    content: "蜂蜜是唯一不會腐壞的食物，考古學家曾在古埃及金字塔中發現 3000 年前的蜂蜜，至今仍可食用！",
    category: "fact",
    tags: ["知識", "有趣"],
  },
  {
    date: "2026-02-09",
    title: "☕ 生活提案",
    content: "試試「番茄工作法」：專注 25 分鐘，休息 5 分鐘，你會發現效率大增！",
    category: "lifehack",
    tags: ["效率", "工作"],
  },
  {
    date: "2026-02-10",
    title: "🎵 音樂推薦",
    content: "聽聽看白噪音或自然音（雨聲、海浪），能幫助你更專注或放鬆。",
    category: "music",
    tags: ["音樂", "放鬆"],
  },
  {
    date: "2026-02-11",
    title: "🌍 旅行靈感",
    content: "冰島的「藍湖溫泉」是世界最美溫泉之一，在雪地中泡溫泉，絕對是夢幻體驗！",
    category: "travel",
    tags: ["旅行", "景點"],
  },
  {
    date: "2026-02-12",
    title: "📚 書籍推薦",
    content: "《原子習慣》教你如何用微小改變創造巨大成就，每天進步 1% 就好！",
    category: "book",
    tags: ["閱讀", "成長"],
  },
  {
    date: "2026-02-13",
    title: "🍳 簡單食譜",
    content: "雞蛋 + 酪梨 + 吐司 = 完美早餐！營養豐富又簡單，5 分鐘搞定。",
    category: "recipe",
    tags: ["美食", "健康"],
  },
  {
    date: "2026-02-14",
    title: "💝 情人節特別版",
    content: "最浪漫的不是昂貴的禮物，而是真心的陪伴和一句「我愛你」。",
    category: "special",
    tags: ["節日", "愛"],
  },
  {
    date: "2026-02-15",
    title: "🎮 遊戲推薦",
    content: "試試《紀念碑谷》，美麗的畫面和創意的關卡設計會讓你驚艷！",
    category: "game",
    tags: ["遊戲", "創意"],
  },
  {
    date: "2026-02-16",
    title: "🧘 正念練習",
    content: "閉上眼睛，深呼吸 3 次，專注在呼吸上，感受當下，釋放壓力。",
    category: "mindfulness",
    tags: ["正念", "放鬆"],
  },
  {
    date: "2026-02-17",
    title: "🎬 電影推薦",
    content: "《心靈捕手》教我們：有時候，我們需要的只是一個真正懂我們的人。",
    category: "movie",
    tags: ["電影", "勵志"],
  },
  {
    date: "2026-02-18",
    title: "🌱 植物小知識",
    content: "虎尾蘭可以在夜間釋放氧氣，是臥室的最佳植物選擇！",
    category: "plant",
    tags: ["植物", "居家"],
  },
  {
    date: "2026-02-19",
    title: "💪 運動挑戰",
    content: "今天做 10 個深蹲！簡單的開始，養成運動習慣。",
    category: "exercise",
    tags: ["運動", "健康"],
  },
  {
    date: "2026-02-20",
    title: "🎨 藝術賞析",
    content: "梵谷的《星夜》充滿動感和情感，據說是他在精神病院時創作的。",
    category: "art",
    tags: ["藝術", "文化"],
  },
  {
    date: "2026-02-21",
    title: "🐱 可愛動物",
    content: "貓咪每天要睡 12-16 小時，難怪牠們總是一副慵懶的樣子！",
    category: "animal",
    tags: ["動物", "可愛"],
  },
  {
    date: "2026-02-22",
    title: "☀️ 好天氣提案",
    content: "今天天氣好嗎？出門走走，曬曬太陽，補充維生素 D！",
    category: "weather",
    tags: ["戶外", "健康"],
  },
  {
    date: "2026-02-23",
    title: "🎯 目標設定",
    content: "把大目標分成小步驟，每完成一步就獎勵自己！",
    category: "goal",
    tags: ["目標", "成長"],
  },
  {
    date: "2026-02-24",
    title: "🌈 心情療癒",
    content: "心情不好時，試試寫下 3 件今天感恩的事，心情會變好喔！",
    category: "healing",
    tags: ["療癒", "正能量"],
  },
  {
    date: "2026-02-25",
    title: "🎓 學習技巧",
    content: "費曼學習法：把學到的東西用簡單的話講給別人聽，就是最好的複習！",
    category: "learning",
    tags: ["學習", "技巧"],
  },
  {
    date: "2026-02-26",
    title: "🌙 睡眠小貼士",
    content: "睡前一小時不看手機，改看紙本書，睡眠品質會更好！",
    category: "sleep",
    tags: ["睡眠", "健康"],
  },
  {
    date: "2026-02-27",
    title: "🎁 送禮靈感",
    content: "最好的禮物是「時間」：陪家人吃飯、陪朋友聊天，都是無價的禮物。",
    category: "gift",
    tags: ["禮物", "關係"],
  },
  {
    date: "2026-02-28",
    title: "🌸 春天來了",
    content: "櫻花季快到了！規劃一下賞櫻行程，感受春天的美好。",
    category: "season",
    tags: ["季節", "自然"],
  },
  {
    date: "2026-03-01",
    title: "📱 數位排毒",
    content: "試試今天不滑社群媒體 1 小時，你會發現時間變多了！",
    category: "digital",
    tags: ["數位", "生活"],
  },
  {
    date: "2026-03-02",
    title: "🎪 趣味活動",
    content: "和朋友玩桌遊，重溫面對面互動的樂趣！",
    category: "activity",
    tags: ["娛樂", "社交"],
  },
  {
    date: "2026-03-03",
    title: "🌟 每日肯定",
    content: "對鏡子說：「我很棒！」自信從肯定自己開始。",
    category: "affirmation",
    tags: ["正能量", "自信"],
  },
  {
    date: "2026-03-04",
    title: "🍰 甜點時光",
    content: "吃一塊喜歡的甜點，好好犒賞自己，快樂很簡單！",
    category: "dessert",
    tags: ["美食", "享受"],
  },
  {
    date: "2026-03-05",
    title: "🎨 手作樂趣",
    content: "試試摺紙或做手工，創作過程本身就很療癒。",
    category: "craft",
    tags: ["手作", "創意"],
  },
  {
    date: "2026-03-06",
    title: "🌊 大自然療癒",
    content: "海邊散步、森林浴，大自然是最好的療癒師。",
    category: "nature",
    tags: ["自然", "放鬆"],
  },
  {
    date: "2026-03-07",
    title: "💌 寫封信",
    content: "手寫一封信給重要的人，比訊息更有溫度。",
    category: "letter",
    tags: ["書寫", "情感"],
  },
];